#pragma once

#define NUMERO_JOGADORES_PLANTEL 20
#define NUMERO_EQUIPAS 18

// Menu constants

enum MENU_INICIAL {

	MENU_INICIAL_OPCAO_NULA = -1,
	MENU_INICIAL_OPCAO_SAIR,
	MENU_INICIAL_OPCAO_CONTINUAR,
	MENU_INICIAL_OPCAO_NOVO_JOGO

};

enum MENU_NOVO_JOGO {

	MENU_NOVO_JOGO_OPCAO_NULA = -1,
	MENU_NOVO_JOGO_OPCAO_SAIR,
	MENU_NOVO_JOGO_OPCAO_INSERIR_NOME,
	MENU_NOVO_JOGO_OPCAO_ESCOLHER_EQUIPA

};
